### ISSUE TITLE
panic: open result.tmpl: no such file or directory

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve-bench#3]
$ ./bleve-bench -count=10000 -source ../../tmp/enwiki.txt 
Using Index Type: upside_down
Using KV store: boltdb
Using KV config: map[string]interface {}{}
2015/10/16 13:17:14 cannot create new index, path already exists
Martys-MacBook-Pro:bleve-bench mschoch$ rm -rf bench.bleve/
Martys-MacBook-Pro:bleve-bench mschoch$ ./bleve-bench -count=10000 -source ../../tmp/enwiki.txt 
Using Index Type: upside_down
Using KV store: boltdb
Using KV config: map[string]interface {}{}
elapsed,docs,avg_single_doc_ms,avg_batched_doc_ms,query_water_matches,first_query_water_ms,avg_repeated5_query_water_ms
9609,1000,27.306334,7.586587,179,0.288680,0.145782
25401,2000,51.266529,11.753098,377,0.264070,0.204048
42722,3000,62.104198,12.289651,600,0.362761,0.303257
61913,4000,74.681389,12.934955,795,0.489658,0.415674
80576,5000,59.854399,14.034485,988,0.596753,0.507052
101146,6000,76.390782,14.281861,1133,0.605886,0.556819
124297,7000,89.616910,15.723442,1314,0.776133,0.648959
148882,8000,74.570839,18.963960,1543,0.848987,0.751525
172786,9000,71.555965,18.553761,1682,0.921988,0.820121
196928,10000,84.169582,17.432221,1873,0.977887,0.911732
panic: open result.tmpl: no such file or directory

goroutine 1 [running]:
main.main()
	/Users/mschoch/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-bench/index.go:79 +0x8de

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/Users/mschoch/Documents/research/gosrc/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82006e120, 0xc82006e180)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 21 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82006e120, 0xc82006e180)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 22 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82006e120, 0xc82006e180)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

goroutine 23 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc82006e120, 0xc82006e180)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:65 +0x14d
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/analysis.go:57 +0xf2

**Comment by mschoch** [comment]
cc @nimishzynga
