### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve-bench#6]
goroutine 1 [running]:
main.doPlot(0xc2089c42f8, 0x1, 0x1, 0x480cfd0, 0x11, 0x47a1f80, 0x4, 0x47b3300, 0x4, 0xc2089cf820, ...)
/Users/sundar/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-bench/plot.go:30 +0x6e
main.main()
/Users/sundar/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-bench/index.go:72 +0x5d5

goroutine 5 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc20805c000, 0xc20805c0c0)
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:70 +0x14c
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:62 +0xd5

goroutine 6 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc20805c000, 0xc20805c0c0)
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:70 +0x14c
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:62 +0xd5

goroutine 7 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc20805c000, 0xc20805c0c0)
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:70 +0x14c
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:62 +0xd5

goroutine 8 [select]:
github.com/blevesearch/bleve/index.AnalysisWorker(0xc20805c000, 0xc20805c0c0)
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:70 +0x14c
created by github.com/blevesearch/bleve/index.NewAnalysisQueue
/Users/sundar/go/src/github.com/blevesearch/bleve/index/analysis.go:62 +0xd5

**Comment by mschoch** [comment]
@nimishzynga can we do 3 things:

1.  Make generation of the plots optional, defaulted to off?  They are causing problems and many uses don't need the plots.
2.  Change the code so that we don't panic, instead we should log the error message and exit cleanly, this allows the underlying KV stores to close properly, otherwise they may die in some unknown state.
3.  Document a fix for this font problem so that people who do want the plots can generate them.

thanks

**Comment by mschoch** [comment]
OK @nimishzynga I've pushed quick fix for 1 and 2 above.  Still need part 3.

**Comment by nimishzynga** [comment]
Plotinum looks for fonts based on the path at which the go get command installs it. If it is moved it after go getting it then they won't be found. (https://groups.google.com/forum/#!topic/golang-nuts/2n8CQZjUYD8). @mschoch should I use different package for plotting the graph or if the above error message is returned to user ? BTW, using dygraph is much easier then plotinum.

**Comment by mschoch** [comment]
I dont know, it does seem to work for me in clean gopath, but I can't imagine I ever moved anything in my main gopath.

In general I prefer not having the plotting so tightly coupled to the testing, but I don't know how dygraph works, so I cant say if thats better or worse.
